import { InputSymbol, StackSymbol, State } from "./pushdownAutomataTypes";
type itemType = State | InputSymbol | StackSymbol;
export declare class FormAutomataBuilder {
    private states;
    private inputSymbols;
    private stackSymbols;
    private initialState?;
    private initialStackSymbol?;
    private acceptingStates;
    private transitionFunctions;
    private statesDiv;
    private inputSymbolDiv;
    private stackSymbolDiv;
    private transitionFunctionDiv;
    private initialStateSelect;
    private initialStackSymbolSelect;
    private acceptingStatesSelect;
    private stateError;
    private inputSymbolError;
    private stackSymbolError;
    private initialStateError;
    private initialStackSymbolError;
    private acceptingStateError;
    private transitionFunctionError;
    constructor();
    registerEvents(): void;
    reset(): void;
    stateFormSubmitHandler(event: SubmitEvent): void;
    inputSymbolSubmitHandler(event: SubmitEvent): void;
    stackSymbolSubmitHandler(event: SubmitEvent): void;
    initialStateChangeHandler(event: Event): void;
    initialStackSymbolChangeHandler(event: Event): void;
    acceptingStateEmptyChangeHandler(event: Event): void;
    acceptingStatesChangeHandler(event: Event): void;
    newItem<T extends itemType>(compareFunction: (arg1: T, arg2: T) => boolean, item: T, type: string): void;
    deleteState(item: State, div: HTMLDivElement): void;
    deleteInputSymbol(item: InputSymbol, div: HTMLDivElement): void;
    deleteStackSymbol(item: StackSymbol, div: HTMLDivElement): void;
    stateAdded(item: State): void;
    inputSymbolAdded(item: InputSymbol): void;
    stackSymbolAdded(item: StackSymbol): void;
    stateDeleted(item: State): void;
    inputSymbolDeleted(item: InputSymbol): void;
    stackSymbolDeleted(item: StackSymbol): void;
}
export {};
